modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/you-may-rest-now/issues"

[[mods]]
modId = "you_may_rest_now"
version = "${file.jarVersion}"
displayName = "You May Rest Now"
displayURL="https://github.com/JamCoreModding/you-may-rest-now"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Allows you to sleep if no monsters can pathfind to you
'''

[[dependencies.you_may_rest_now]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.you_may_rest_now]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.you_may_rest_now]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.you_may_rest_now]]
modId = "jamlib"
mandatory = true
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"
