modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/you-may-rest-now/issues"

[[mods]]
modId = "you_may_rest_now"
version = "${file.jarVersion}"
displayName = "You May Rest Now"
displayURL="https://github.com/JamCoreModding/you-may-rest-now"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Allows you to sleep if no monsters can pathfind to you
'''

[[dependencies.you_may_rest_now]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.you_may_rest_now]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.you_may_rest_now]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.you_may_rest_now]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "you_may_rest_now.mixins.json"
